### ISSUE TITLE
[1.10.2] NoSuchFieldException: jeiConfigurationDir

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [elix-x/Excore#3] opened 2016-10-23 20:52 UTC
looks like the latest JEI removed a field that Excore is attempting to reference through FEI.
[crash-2016-10-23_13.41.11-client.txt](https://github.com/Elix-x/Excore/files/546627/crash-2016-10-23_13.41.11-client.txt)
[fml-client-latest.log.txt](https://github.com/Elix-x/Excore/files/546628/fml-client-latest.log.txt)

_update: rollback to jei_1.10.2-3.12.8.327.jar seems to include the field in question._

**Comment by Elix-x** [comment] 2016-10-24 07:55
Known.
Belongs to FEI.
Duplicate of Elix-x/Forever-Enough-Items#50.

**Closed as completed by Elix-x** 2016-10-24 07:55 UTC
Labels: duplicate
